# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatapp_pb2 as chatapp__pb2


class ChatAppStub(object):
    """Chat app service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createAccount = channel.unary_unary(
                '/chatapp.ChatApp/createAccount',
                request_serializer=chatapp__pb2.Account.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )
        self.logIn = channel.unary_unary(
                '/chatapp.ChatApp/logIn',
                request_serializer=chatapp__pb2.Account.SerializeToString,
                response_deserializer=chatapp__pb2.LoginReply.FromString,
                )
        self.listAccounts = channel.unary_unary(
                '/chatapp.ChatApp/listAccounts',
                request_serializer=chatapp__pb2.Empty.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )
        self.filterAccounts = channel.unary_unary(
                '/chatapp.ChatApp/filterAccounts',
                request_serializer=chatapp__pb2.FilterString.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )
        self.sendMessage = channel.unary_unary(
                '/chatapp.ChatApp/sendMessage',
                request_serializer=chatapp__pb2.Message.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )
        self.deleteAccount = channel.unary_unary(
                '/chatapp.ChatApp/deleteAccount',
                request_serializer=chatapp__pb2.Account.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )
        self.listenForMessages = channel.unary_stream(
                '/chatapp.ChatApp/listenForMessages',
                request_serializer=chatapp__pb2.Account.SerializeToString,
                response_deserializer=chatapp__pb2.Message.FromString,
                )
        self.listenForReplies = channel.unary_stream(
                '/chatapp.ChatApp/listenForReplies',
                request_serializer=chatapp__pb2.Empty.SerializeToString,
                response_deserializer=chatapp__pb2.ServerReply.FromString,
                )


class ChatAppServicer(object):
    """Chat app service definition.
    """

    def createAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listenForMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listenForReplies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.createAccount,
                    request_deserializer=chatapp__pb2.Account.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
            'logIn': grpc.unary_unary_rpc_method_handler(
                    servicer.logIn,
                    request_deserializer=chatapp__pb2.Account.FromString,
                    response_serializer=chatapp__pb2.LoginReply.SerializeToString,
            ),
            'listAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.listAccounts,
                    request_deserializer=chatapp__pb2.Empty.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
            'filterAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.filterAccounts,
                    request_deserializer=chatapp__pb2.FilterString.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=chatapp__pb2.Message.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
            'deleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAccount,
                    request_deserializer=chatapp__pb2.Account.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
            'listenForMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.listenForMessages,
                    request_deserializer=chatapp__pb2.Account.FromString,
                    response_serializer=chatapp__pb2.Message.SerializeToString,
            ),
            'listenForReplies': grpc.unary_stream_rpc_method_handler(
                    servicer.listenForReplies,
                    request_deserializer=chatapp__pb2.Empty.FromString,
                    response_serializer=chatapp__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatapp.ChatApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatApp(object):
    """Chat app service definition.
    """

    @staticmethod
    def createAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/createAccount',
            chatapp__pb2.Account.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def logIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/logIn',
            chatapp__pb2.Account.SerializeToString,
            chatapp__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/listAccounts',
            chatapp__pb2.Empty.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def filterAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/filterAccounts',
            chatapp__pb2.FilterString.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/sendMessage',
            chatapp__pb2.Message.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatapp.ChatApp/deleteAccount',
            chatapp__pb2.Account.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listenForMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chatapp.ChatApp/listenForMessages',
            chatapp__pb2.Account.SerializeToString,
            chatapp__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listenForReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chatapp.ChatApp/listenForReplies',
            chatapp__pb2.Empty.SerializeToString,
            chatapp__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
